
/**************************************************************
 *	
 *	Coin, 8 bit, 11025Hz,
 *	1 channel, 4621 bytes/channel
 *	Total Size: 1 * 4621 + 4 (header) = 4665 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Andrew\Desktop\Second Year\cs2261\Final Project\M03\AndrewLee_FinalProject\Coin.wav
 *	Time-stamp: Fri Nov 24 13:54:42 2017
 *	
 **************************************************************/

#ifndef __COINH__
#define __COINH__

#define COINFREQ 11025
#define COINLEN 4621

extern const unsigned char Coin[4621];

#endif /* __COINH__ */
