
/**************************************************************
 *	
 *	FishtankBubbles, 8 bit, 11025Hz,
 *	1 channel, 259776 bytes/channel
 *	Total Size: 1 * 259776 + 4 (header) = 259820 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Andrew\Desktop\Second Year\cs2261\Final Project\M03\AndrewLee_FinalProject\FishtankBubbles.wav
 *	Time-stamp: Fri Nov 24 13:23:24 2017
 *	
 **************************************************************/

#ifndef __FISHTANKBUBBLESH__
#define __FISHTANKBUBBLESH__

#define FISHTANKBUBBLESFREQ 11025
#define FISHTANKBUBBLESLEN 259776

extern const unsigned char FishtankBubbles[259776];

#endif /* __FISHTANKBUBBLESH__ */
