
/**************************************************************
 *	
 *	FUNsong, 8 bit, 11025Hz,
 *	1 channel, 1176576 bytes/channel
 *	Total Size: 1 * 1176576 + 4 (header) = 1176620 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Andrew\Desktop\Second Year\cs2261\Final Project\M03\AndrewLee_FinalProject\FUNsong.wav
 *	Time-stamp: Fri Nov 24 13:38:51 2017
 *	
 **************************************************************/

#ifndef __FUNSONGH__
#define __FUNSONGH__

#define FUNSONGFREQ 11025
#define FUNSONGLEN 1176576

extern const unsigned char FUNsong[1176576];

#endif /* __FUNSONGH__ */
