
/**************************************************************
 *	
 *	Money, 8 bit, 11025Hz,
 *	1 channel, 19845 bytes/channel
 *	Total Size: 1 * 19845 + 4 (header) = 19889 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Andrew\Desktop\Second Year\cs2261\Final Project\M03\AndrewLee_FinalProject\Money.wav
 *	Time-stamp: Fri Nov 24 14:22:06 2017
 *	
 **************************************************************/

#ifndef __MONEYH__
#define __MONEYH__

#define MONEYFREQ 11025
#define MONEYLEN 19845

extern const unsigned char Money[19845];

#endif /* __MONEYH__ */
