
/**************************************************************
 *	
 *	Screaming, 8 bit, 11025Hz,
 *	1 channel, 31929 bytes/channel
 *	Total Size: 1 * 31929 + 4 (header) = 31973 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Andrew\Desktop\Second Year\cs2261\Final Project\Final Submission\AndrewLee_FinalProject\Screaming.wav
 *	Time-stamp: Sat Dec 02 13:45:18 2017
 *	
 **************************************************************/

#ifndef __SCREAMINGH__
#define __SCREAMINGH__

#define SCREAMINGFREQ 11025
#define SCREAMINGLEN 31929

extern const unsigned char Screaming[31929];

#endif /* __SCREAMINGH__ */
