
/**************************************************************
 *	
 *	Technique, 8 bit, 11025Hz,
 *	1 channel, 387072 bytes/channel
 *	Total Size: 1 * 387072 + 4 (header) = 387116 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Andrew\Desktop\Second Year\cs2261\Final Project\M03\AndrewLee_FinalProject\Technique.wav
 *	Time-stamp: Fri Nov 24 14:28:07 2017
 *	
 **************************************************************/

#ifndef __TECHNIQUEH__
#define __TECHNIQUEH__

#define TECHNIQUEFREQ 11025
#define TECHNIQUELEN 387072

extern const unsigned char Technique[387072];

#endif /* __TECHNIQUEH__ */
