
/**************************************************************
 *	
 *	Thunder, 8 bit, 11025Hz,
 *	1 channel, 26460 bytes/channel
 *	Total Size: 1 * 26460 + 4 (header) = 26504 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Andrew\Desktop\Second Year\cs2261\Final Project\M03\AndrewLee_FinalProject\Thunder.wav
 *	Time-stamp: Fri Nov 24 14:28:03 2017
 *	
 **************************************************************/

#ifndef __THUNDERH__
#define __THUNDERH__

#define THUNDERFREQ 11025
#define THUNDERLEN 26460

extern const unsigned char Thunder[26460];

#endif /* __THUNDERH__ */
