
/**************************************************************
 *	
 *	Tomfoolery, 8 bit, 11025Hz,
 *	1 channel, 1399104 bytes/channel
 *	Total Size: 1 * 1399104 + 4 (header) = 1399148 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Andrew\Desktop\Second Year\cs2261\Final Project\M03\AndrewLee_FinalProject\Tomfoolery.wav
 *	Time-stamp: Fri Nov 24 13:38:42 2017
 *	
 **************************************************************/

#ifndef __TOMFOOLERYH__
#define __TOMFOOLERYH__

#define TOMFOOLERYFREQ 11025
#define TOMFOOLERYLEN 1399104

extern const unsigned char Tomfoolery[1399104];

#endif /* __TOMFOOLERYH__ */
