
/**************************************************************
 *	
 *	Whoosh, 8 bit, 11025Hz,
 *	1 channel, 5578 bytes/channel
 *	Total Size: 1 * 5578 + 4 (header) = 5622 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Andrew\Desktop\Second Year\cs2261\Final Project\M03\AndrewLee_FinalProject\Whoosh.wav
 *	Time-stamp: Fri Nov 24 14:31:59 2017
 *	
 **************************************************************/

#ifndef __WHOOSHH__
#define __WHOOSHH__

#define WHOOSHFREQ 11025
#define WHOOSHLEN 5578

extern const unsigned char Whoosh[5578];

#endif /* __WHOOSHH__ */
